// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ2uisN34aKHiMpNjysOycupBUXW03PLY',
    appId: '1:879649532829:web:c8c6fbfc330d51d85add74',
    messagingSenderId: '879649532829',
    projectId: 'delivery-app-79bf7',
    authDomain: 'delivery-app-79bf7.firebaseapp.com',
    storageBucket: 'delivery-app-79bf7.firebasestorage.app',
    measurementId: 'G-66DW45LH0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFSCeZQ6V8nQ6NQGkrGL44YFCuwBljqgc',
    appId: '1:879649532829:android:bb298b68df050ba15add74',
    messagingSenderId: '879649532829',
    projectId: 'delivery-app-79bf7',
    storageBucket: 'delivery-app-79bf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaA9Xqk8gJYXNWxJ2DuJ8lGJxUuvGuHcw',
    appId: '1:879649532829:ios:be23b38d9a0c3d475add74',
    messagingSenderId: '879649532829',
    projectId: 'delivery-app-79bf7',
    storageBucket: 'delivery-app-79bf7.firebasestorage.app',
    iosBundleId: 'com.example.edaraDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaA9Xqk8gJYXNWxJ2DuJ8lGJxUuvGuHcw',
    appId: '1:879649532829:ios:be23b38d9a0c3d475add74',
    messagingSenderId: '879649532829',
    projectId: 'delivery-app-79bf7',
    storageBucket: 'delivery-app-79bf7.firebasestorage.app',
    iosBundleId: 'com.example.edaraDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ2uisN34aKHiMpNjysOycupBUXW03PLY',
    appId: '1:879649532829:web:9e0be187941d8d085add74',
    messagingSenderId: '879649532829',
    projectId: 'delivery-app-79bf7',
    authDomain: 'delivery-app-79bf7.firebaseapp.com',
    storageBucket: 'delivery-app-79bf7.firebasestorage.app',
    measurementId: 'G-J9D1SBXWFH',
  );
}
